-------------------------------------
--Add data using Restaurant Package
-------------------------------------
CLEAR SCREEN;
--Add restaurant details
EXEC RESTAURANT_PACKAGE.UPSERT_RESTAURANT(NULL, 'Burger Hub', TO_DATE('10:00:00', 'HH24:MI:SS'), TO_DATE('23:59:59', 'HH24:MI:SS'));
EXEC RESTAURANT_PACKAGE.UPSERT_RESTAURANT(NULL, 'Seafood Delight', TO_DATE('11:00:00', 'HH24:MI:SS'), TO_DATE('22:00:00', 'HH24:MI:SS'));
EXEC RESTAURANT_PACKAGE.UPSERT_RESTAURANT(NULL, 'Mountain View Cafe', TO_DATE('07:30:00', 'HH24:MI:SS'), TO_DATE('20:00:00', 'HH24:MI:SS'));
EXEC RESTAURANT_PACKAGE.UPSERT_RESTAURANT(NULL, 'Urban Eats', TO_DATE('09:00:00', 'HH24:MI:SS'), TO_DATE('23:30:00', 'HH24:MI:SS'));
EXEC RESTAURANT_PACKAGE.UPSERT_RESTAURANT(NULL, 'Garden Bistro', TO_DATE('08:00:00', 'HH24:MI:SS'), TO_DATE('21:30:00', 'HH24:MI:SS'));

--Add Branch Address
EXEC RESTAURANT_PACKAGE.UPSERT_BRANCH_ADDRESS(NULL, 'R1', 9876543210, '123 Burger St', 'Suite 101', 'CityG', 'StateG', '78901');
EXEC RESTAURANT_PACKAGE.UPSERT_BRANCH_ADDRESS(NULL, 'R2', 8765432190, '456 Seafood Rd', 'Suite 102', 'CityH', 'StateH', '89012');
EXEC RESTAURANT_PACKAGE.UPSERT_BRANCH_ADDRESS(NULL, 'R3', 7654321980, '789 Cafe Blvd', 'Suite 103', 'CityI', 'StateI', '90123');
EXEC RESTAURANT_PACKAGE.UPSERT_BRANCH_ADDRESS(NULL, 'R3', 6543219870, '135 Urban Way', 'Suite 104', 'CityJ', 'StateJ', '01234');
EXEC RESTAURANT_PACKAGE.UPSERT_BRANCH_ADDRESS(NULL, 'R4', 5432198760, '246 Bistro Ln', 'Suite 105', 'CityK', 'StateK', '12345');
EXEC RESTAURANT_PACKAGE.UPSERT_BRANCH_ADDRESS(NULL, 'R5', 4321987650, '369 Diner Ave', 'Suite 106', 'CityL', 'StateL', '23456');
	 
--Add Items
EXEC RESTAURANT_PACKAGE.UPSERT_ITEM(NULL, 'R1', 'Chicken Sandwich', 6.99);
EXEC RESTAURANT_PACKAGE.UPSERT_ITEM(NULL, 'R1', 'Caesar Salad', 8.99);
EXEC RESTAURANT_PACKAGE.UPSERT_ITEM(NULL, 'R1', 'French Fries', 3.99);
EXEC RESTAURANT_PACKAGE.UPSERT_ITEM(NULL, 'R1', 'Chocolate Shake', 4.99);
			  
EXEC RESTAURANT_PACKAGE.UPSERT_ITEM(NULL, 'R2', 'Margherita Pizza', 10.99);
EXEC RESTAURANT_PACKAGE.UPSERT_ITEM(NULL, 'R2', 'Pasta Alfredo', 7.99);
EXEC RESTAURANT_PACKAGE.UPSERT_ITEM(NULL, 'R2', 'Garlic Bread', 4.50);
EXEC RESTAURANT_PACKAGE.UPSERT_ITEM(NULL, 'R2', 'Tiramisu', 6.99);
		  
EXEC RESTAURANT_PACKAGE.UPSERT_ITEM(NULL, 'R3', 'BBQ Ribs', 15.99);
EXEC RESTAURANT_PACKAGE.UPSERT_ITEM(NULL, 'R3', 'Shrimp Scampi', 11.99);
EXEC RESTAURANT_PACKAGE.UPSERT_ITEM(NULL, 'R3', 'Mashed Potatoes', 3.99);
EXEC RESTAURANT_PACKAGE.UPSERT_ITEM(NULL, 'R3', 'Cheesecake', 5.99);
			  
EXEC RESTAURANT_PACKAGE.UPSERT_ITEM(NULL, 'R4', 'Steak Fajitas', 13.99);
EXEC RESTAURANT_PACKAGE.UPSERT_ITEM(NULL, 'R4', 'Chicken Quesadilla', 8.99);
EXEC RESTAURANT_PACKAGE.UPSERT_ITEM(NULL, 'R4', 'Guacamole', 2.99);
EXEC RESTAURANT_PACKAGE.UPSERT_ITEM(NULL, 'R4', 'Salsa and Chips', 3.50);
	  
EXEC RESTAURANT_PACKAGE.UPSERT_ITEM(NULL, 'R5', 'Espresso', 2.99);
EXEC RESTAURANT_PACKAGE.UPSERT_ITEM(NULL, 'R5', 'Chocolate Croissant', 3.99);
EXEC RESTAURANT_PACKAGE.UPSERT_ITEM(NULL, 'R5', 'Fruit Salad', 4.50);
EXEC RESTAURANT_PACKAGE.UPSERT_ITEM(NULL, 'R5', 'Iced Latte', 5.99); 

--Add promo codes
EXEC RESTAURANT_PACKAGE.UPSERT_PROMO_CODE(NULL, 10);
EXEC RESTAURANT_PACKAGE.UPSERT_PROMO_CODE(NULL, 15);
EXEC RESTAURANT_PACKAGE.UPSERT_PROMO_CODE(NULL, 20);
EXEC RESTAURANT_PACKAGE.UPSERT_PROMO_CODE(NULL, 5);
EXEC RESTAURANT_PACKAGE.UPSERT_PROMO_CODE(NULL, 25);
EXEC RESTAURANT_PACKAGE.UPSERT_PROMO_CODE(NULL, 30);
	
--Add restaurant promo
EXEC RESTAURANT_PACKAGE.UPSERT_RESTAURANT_PROMO(NULL, 'PR1', 'R1');
EXEC RESTAURANT_PACKAGE.UPSERT_RESTAURANT_PROMO(NULL, 'PR2', 'R2');
EXEC RESTAURANT_PACKAGE.UPSERT_RESTAURANT_PROMO(NULL, 'PR3', 'R3');
EXEC RESTAURANT_PACKAGE.UPSERT_RESTAURANT_PROMO(NULL, 'PR4', 'R4');
EXEC RESTAURANT_PACKAGE.UPSERT_RESTAURANT_PROMO(NULL, 'PR5', 'R5');