--Execution Order:4
--User: SwadKhajana_admin

CLEAR SCREEN;
/*
CREATE RESTAURANT USER
*/
set SERVEROUTPUT on

BEGIN
    EXECUTE IMMEDIATE 'DROP USER RESTAURANT_SK CASCADE';
    dbms_output.put_line('USER RESTAURANT_SK DROPPED');
EXCEPTION
    WHEN OTHERS THEN
        dbms_output.put_line('USER RESTAURANT_SK DOES NOT EXIST');
END;
/

CREATE USER RESTAURANT_SK IDENTIFIED BY SKRestaurant123;

ALTER USER RESTAURANT_SK
    QUOTA UNLIMITED ON data;

GRANT connect, resource TO RESTAURANT_SK WITH ADMIN OPTION; 


/*
CREATE CUSTOMER USER
*/
BEGIN
    EXECUTE IMMEDIATE 'DROP USER CUSTOMER_SK CASCADE';
    dbms_output.put_line('USER CUSTOMER_SK DROPPED');
EXCEPTION
    WHEN OTHERS THEN
        dbms_output.put_line('USER CUSTOMER_SK DOES NOT EXIST');
END;
/

CREATE USER CUSTOMER_SK IDENTIFIED BY SKCustomer123;

ALTER USER CUSTOMER_SK
    QUOTA UNLIMITED ON data;

GRANT connect, resource TO CUSTOMER_SK;


/*
CREATE DELIVERY EXECUTIVE USER
*/
BEGIN
    EXECUTE IMMEDIATE 'DROP USER DELIVERY_EXEC_SK CASCADE';
    dbms_output.put_line('USER DELIVERY_EXEC_SK DROPPED');
EXCEPTION
    WHEN OTHERS THEN
        dbms_output.put_line('USER DELIVERY_EXEC_SK DOES NOT EXIST');
END;
/

CREATE USER DELIVERY_EXEC_SK IDENTIFIED BY SKDeliveryexec123;

ALTER USER DELIVERY_EXEC_SK
    QUOTA UNLIMITED ON data;

GRANT connect, resource TO DELIVERY_EXEC_SK;